### ISSUE TITLE
Build instructions do not build

### ISSUE THREAD

**Issue by fbrier** [breese/aware#4]
The instructions imply cloning the repo, and invoking "cmake" from the "aware" directory.  However, cmake complains, "Specify a source directory to (re-)generate a build system for it in the current working directory.  Specify an existing build directory to re-generate its build system."  Perhaps the build process changed from when the README.md file was written?  Invoking "cmake avahi" from the ./aware/src directory causes some files to be built, but not a library, or the examples.  Any help would be appreciated.  Thank you.

**Comment by breese** [comment]
The README.md instructions works just fine here. My cmake (version 3.5.1) does not complain.

An alternative is to use the following from the aware root

```
cmake -H. -Bbuild
cd build
make
```
